runtime: python27
api_version: 1
threadsafe: yes
default_expiration: "0s"

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /index\.html
  static_files: web/index.html
  upload: web/index\.html

- url: /web
  static_dir: web

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest